In [2]:
import pandas as pd
dt = pd.read_csv('train_data.csv')

dt.head()

Id  age     workclass  fnlwgt     education  education.num  \
0  16280   34       Private  204991  Some-college             10   
1  16281   58     Local-gov  310085          10th              6   
2  16282   25       Private  146117  Some-college             10   
3  16283   24       Private  138938  Some-college             10   
4  16284   57  Self-emp-inc  258883       HS-grad              9   

       marital.status         occupation   relationship   race     sex  \
0            Divorced    Exec-managerial      Own-child  White    Male   
1  Married-civ-spouse   Transport-moving        Husband  White    Male   
2       Never-married  Machine-op-inspct  Not-in-family  White    Male   
3            Divorced       Adm-clerical  Not-in-family  White  Female   
4  Married-civ-spouse   Transport-moving        Husband  White    Male   

   capital.gain  capital.loss  hours.per.week native.country income  
0             0             0              44  United-States  <=50K  
1             0             0              40  United-States  <=50K  
2             0             0              42  United-States  <=50K  
3             0             0              40  United-States  <=50K  
4          5178             0              60        Hungary   >50K

In [3]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32560 entries, 0 to 32559
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Id              32560 non-null  int64 
 1   age             32560 non-null  int64 
 2   workclass       32560 non-null  object
 3   fnlwgt          32560 non-null  int64 
 4   education       32560 non-null  object
 5   education.num   32560 non-null  int64 
 6   marital.status  32560 non-null  object
 7   occupation      32560 non-null  object
 8   relationship    32560 non-null  object
 9   race            32560 non-null  object
 10  sex             32560 non-null  object
 11  capital.gain    32560 non-null  int64 
 12  capital.loss    32560 non-null  int64 
 13  hours.per.week  32560 non-null  int64 
 14  native.country  32560 non-null  object
 15  income          32560 non-null  object
dtypes: int64(7), object(9)
memory usage: 4.0+ MB


In [4]:
dt.describe()

Id           age        fnlwgt  education.num  capital.gain  \
count  32560.000000  32560.000000  3.256000e+04   32560.000000  32560.000000   
mean   32559.500000     38.581634  1.897818e+05      10.080590   1077.615172   
std     9399.406719     13.640642  1.055498e+05       2.572709   7385.402999   
min    16280.000000     17.000000  1.228500e+04       1.000000      0.000000   
25%    24419.750000     28.000000  1.178315e+05       9.000000      0.000000   
50%    32559.500000     37.000000  1.783630e+05      10.000000      0.000000   
75%    40699.250000     48.000000  2.370545e+05      12.000000      0.000000   
max    48839.000000     90.000000  1.484705e+06      16.000000  99999.000000   

       capital.loss  hours.per.week  
count  32560.000000    32560.000000  
mean      87.306511       40.437469  
std      402.966116       12.347618  
min        0.000000        1.000000  
25%        0.000000       40.000000  
50%        0.000000       40.000000  
75%        0.000000       45.000000  
max     4356.000000       99.000000

In [5]:
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
dt_analise = dt.copy()

In [7]:
# Importando o LabelEncoder
from sklearn.preprocessing import LabelEncoder

# Instanciando o LabelEncoder
le = LabelEncoder()

# Modificando o nosso dataframe, transformando a variável de classe em 0s e 1s
dt_analise['income'] = le.fit_transform(dt_analise['income'])

In [8]:
dt_analise['income']

0        0
1        0
2        0
3        0
4        1
        ..
32555    1
32556    0
32557    0
32558    0
32559    0
Name: income, Length: 32560, dtype: int32

In [9]:
dt.drop_duplicates(keep='first', inplace=True)

In [10]:
dt.head()

Id  age     workclass  fnlwgt     education  education.num  \
0  16280   34       Private  204991  Some-college             10   
1  16281   58     Local-gov  310085          10th              6   
2  16282   25       Private  146117  Some-college             10   
3  16283   24       Private  138938  Some-college             10   
4  16284   57  Self-emp-inc  258883       HS-grad              9   

       marital.status         occupation   relationship   race     sex  \
0            Divorced    Exec-managerial      Own-child  White    Male   
1  Married-civ-spouse   Transport-moving        Husband  White    Male   
2       Never-married  Machine-op-inspct  Not-in-family  White    Male   
3            Divorced       Adm-clerical  Not-in-family  White  Female   
4  Married-civ-spouse   Transport-moving        Husband  White    Male   

   capital.gain  capital.loss  hours.per.week native.country income  
0             0             0              44  United-States  <=50K  
1             0             0              40  United-States  <=50K  
2             0             0              42  United-States  <=50K  
3             0             0              40  United-States  <=50K  
4          5178             0              60        Hungary   >50K

In [32]:
Y_train = dt.pop('income')

X_train = dt

KeyError: 'income'

daqui pra baixo é do cara

In [16]:
dt_treinamento_x.head()

Id  age     workclass  fnlwgt     education  education.num  \
0  16280   34       Private  204991  Some-college             10   
1  16281   58     Local-gov  310085          10th              6   
2  16282   25       Private  146117  Some-college             10   
3  16283   24       Private  138938  Some-college             10   
4  16284   57  Self-emp-inc  258883       HS-grad              9   

       marital.status         occupation   relationship   race     sex  \
0            Divorced    Exec-managerial      Own-child  White    Male   
1  Married-civ-spouse   Transport-moving        Husband  White    Male   
2       Never-married  Machine-op-inspct  Not-in-family  White    Male   
3            Divorced       Adm-clerical  Not-in-family  White  Female   
4  Married-civ-spouse   Transport-moving        Husband  White    Male   

   capital.gain  capital.loss  hours.per.week native.country  
0             0             0              44  United-States  
1             0             0              40  United-States  
2             0             0              42  United-States  
3             0             0              40  United-States  
4          5178             0              60        Hungary

In [12]:
import numpy as np
# Seleciona as variáveis numéricas
numerical_cols = list(X_train.select_dtypes(include=[np.number]).columns.values)

# Remove as variáveis numéricas esparsas
numerical_cols.remove('capital.gain')
numerical_cols.remove('capital.loss')

# Seleciona as variáveis numéricas esparsas
sparse_cols = ['capital.gain', 'capital.loss']

# Seleciona as variáveis categóricas
categorical_cols = list(X_train.select_dtypes(exclude=[np.number]).columns.values)

# Mostrando as diferentes seleções
print("Colunas numéricas: ", numerical_cols)
print("Colunas esparsas: ", sparse_cols)
print("Colunas categóricas: ", categorical_cols)

Colunas numéricas:  ['Id', 'age', 'fnlwgt', 'education.num', 'hours.per.week']
Colunas esparsas:  ['capital.gain', 'capital.loss']
Colunas categóricas:  ['workclass', 'education', 'marital.status', 'occupation', 'relationship', 'race', 'sex', 'native.country']


In [17]:
from sklearn.impute import SimpleImputer

# Inicializa nosso Imputer
simple_imputer = SimpleImputer(strategy='most_frequent')

In [18]:
# Cria um array com um dado faltante
array = np.array([["Female"],
         ["Male"],
         [np.nan],
         ["Female"]], dtype=object)

# Preenche o dado faltante com o Imputer
new_array = simple_imputer.fit_transform(array)

print(new_array)

[['Female']
 ['Male']
 ['Female']
 ['Female']]


In [19]:
from sklearn.preprocessing import OneHotEncoder

# Inicializa nosso Encoder
one_hot = OneHotEncoder(sparse=False)

In [20]:
# Cria um array com dados categóricos
array = np.array([["Female"],
         ["Male"],
         ["Female"],
         ["Female"]], dtype=object)

# Transforma o nosso array
new_array = one_hot.fit_transform(array)

new_array

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.]])

In [21]:
from sklearn.pipeline import Pipeline

# Cria a nossa pipeline categórica
categorical_pipeline = Pipeline(steps = [
    ('imputer', SimpleImputer(strategy = 'most_frequent')),
    ('onehot', OneHotEncoder(drop='if_binary'))
])

In [22]:
# Cria um array com dados categóricos
array = np.array([["Female"],
         ["Male"],
         [np.nan],
         ["Female"]], dtype=object)

# Transforma o nosso array
new_array = categorical_pipeline.fit_transform(array)

In [23]:
from sklearn.impute import KNNImputer

# Cria o nosso KNNImputer com 5 vizinhos
knn_imputer = KNNImputer(n_neighbors=5)

In [24]:
# Cria o nosso array com dados faltantes
array = [[1, 2, np.nan], [3, 4, 3], [np.nan, 6, 5], [8, 8, 7]]

# Preenche os dados faltantes
new_array = knn_imputer.fit_transform(array)

new_array

array([[1., 2., 5.],
       [3., 4., 3.],
       [4., 6., 5.],
       [8., 8., 7.]])

In [25]:
from sklearn.preprocessing import StandardScaler

# Cria o nosso StandardScaler
scaler = StandardScaler()

In [26]:
# Cria um array numérico
array = [[-3, 0], [0, 0], [3, 1], [0, 1]]

# Normaliza nosso array
new_array = scaler.fit_transform(array)

new_array

array([[-1.41421356, -1.        ],
       [ 0.        , -1.        ],
       [ 1.41421356,  1.        ],
       [ 0.        ,  1.        ]])

In [27]:
# Cria a nossa pipeline numérica
numerical_pipeline = Pipeline(steps = [
    ('imputer', KNNImputer(n_neighbors=10, weights="uniform")),
    ('scaler', StandardScaler())
])

In [28]:
from sklearn.preprocessing import RobustScaler

sparse_pipeline = Pipeline(steps = [
    ('imputer', KNNImputer(n_neighbors=10, weights="uniform")),
    ('scaler', RobustScaler())
])

In [29]:
from sklearn.compose import ColumnTransformer

# Cria o nosso Pré-Processador

# Cada pipeline está associada a suas respectivas colunas no datast
preprocessor = ColumnTransformer(transformers = [
    ('num', numerical_pipeline, numerical_cols),
    ('spr', sparse_pipeline, sparse_cols),
    ('cat', categorical_pipeline, categorical_cols)
])

In [30]:
X_train = preprocessor.fit_transform(X_train)